version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "YASTREBOVIA_204"
      POSTGRES_USER: "YASTREBOVIA_204"
      POSTGRES_PASSWORD: "YASTREBOVIA_204"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgres/data
    ports:  
      - "6000:5432"